#!/bin/bash
# Multipass VM provider helper for integration tests
# This script helps Multipass users quickly set up test VMs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_INV_DIR="$(cd "$SCRIPT_DIR/../inventory" && pwd)"

# Multipass doesn't support Rocky, so we use Ubuntu
IMAGE="22.04"
CPUS="2"
MEMORY="2G"
DISK="10G"

create_vms() {
    echo "Creating Multipass test VMs (Ubuntu $IMAGE)..."
    multipass launch "$IMAGE" --name test-postgresql --cpus "$CPUS" --memory "$MEMORY" --disk "$DISK" || echo "test-postgresql may already exist"
    multipass launch "$IMAGE" --name test-mattermost --cpus "$CPUS" --memory "$MEMORY" --disk "$DISK" || echo "test-mattermost may already exist"
    multipass launch "$IMAGE" --name test-rtcd --cpus "$CPUS" --memory "$MEMORY" --disk "$DISK" || echo "test-rtcd may already exist"
    echo "✓ Test VMs created"
}

delete_vms() {
    echo "Deleting Multipass test VMs..."
    multipass delete test-postgresql test-mattermost test-rtcd 2>/dev/null || true
    multipass purge 2>/dev/null || true
    echo "✓ Test VMs deleted"
}

setup_inventory() {
    local username="ubuntu"  # Default Multipass user
    local test_ini="$TEST_INV_DIR/test.ini"

    echo "Creating test inventory at $test_ini..."

    # Get IP addresses
    local pg_ip=$(multipass info test-postgresql --format csv | tail -1 | cut -d',' -f3)
    local mm_ip=$(multipass info test-mattermost --format csv | tail -1 | cut -d',' -f3)
    local rtcd_ip=$(multipass info test-rtcd --format csv | tail -1 | cut -d',' -f3)

    cat > "$test_ini" <<EOF
# Integration test inventory - Multipass
# Auto-generated by vm-providers/multipass.sh

[database]
test-postgresql ansible_host=$pg_ip ansible_user=$username

[app]
test-mattermost ansible_host=$mm_ip ansible_user=$username

[rtcd]
test-rtcd ansible_host=$rtcd_ip ansible_user=$username

[mattermost:children]
database
app
rtcd

[mattermost:vars]
ansible_python_interpreter=/usr/bin/python3
environment=test
EOF
    echo "✓ Test inventory created"
}

verify_vms() {
    echo "Verifying VM connectivity..."
    multipass list | grep -E "test-(postgresql|mattermost|rtcd)" || {
        echo "❌ Test VMs not found. Run: $0 create"
        exit 1
    }
    echo "✓ VMs are running"
}

case "${1:-}" in
    create)
        create_vms
        sleep 5  # Give VMs time to fully start
        setup_inventory
        echo ""
        echo "Next steps:"
        echo "  1. Verify VMs: make test-integration-check-vms"
        echo "  2. Run tests: make test-integration"
        ;;
    delete)
        delete_vms
        ;;
    setup-inventory)
        setup_inventory
        ;;
    verify)
        verify_vms
        ;;
    *)
        echo "Usage: $0 {create|delete|setup-inventory|verify}"
        echo ""
        echo "Commands:"
        echo "  create           Create test VMs and generate test.ini"
        echo "  delete           Delete test VMs"
        echo "  setup-inventory  Generate test.ini (VMs must exist)"
        echo "  verify           Check if test VMs are running"
        exit 1
        ;;
esac
