#!/bin/bash
# OrbStack VM provider helper for integration tests
# This script helps OrbStack users quickly set up test VMs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_INV_DIR="$(cd "$SCRIPT_DIR/../inventory" && pwd)"

create_vms() {
    echo "Creating OrbStack test VMs (Rocky Linux 9, AMD64)..."
    orb create -a amd64 rocky:9 test-postgresql || echo "test-postgresql may already exist"
    orb create -a amd64 rocky:9 test-mattermost || echo "test-mattermost may already exist"
    orb create -a amd64 rocky:9 test-rtcd || echo "test-rtcd may already exist"
    echo "✓ Test VMs created"
}

delete_vms() {
    echo "Deleting OrbStack test VMs..."
    orb delete -f test-postgresql test-mattermost test-rtcd 2>/dev/null || true
    echo "✓ Test VMs deleted"
}

setup_inventory() {
    local username="${USER}"
    local test_ini="$TEST_INV_DIR/test.ini"

    echo "Creating test inventory at $test_ini..."
    cat > "$test_ini" <<EOF
# Integration test inventory - OrbStack
# Auto-generated by vm-providers/orbstack.sh

[database]
${username}@test-postgresql@orb

[app]
${username}@test-mattermost@orb

[rtcd]
${username}@test-rtcd@orb

[mattermost:children]
database
app
rtcd

[mattermost:vars]
ansible_python_interpreter=/usr/bin/python3
environment=test
EOF
    echo "✓ Test inventory created"
}

verify_vms() {
    echo "Verifying VM connectivity..."
    orb list | grep -E "test-(postgresql|mattermost|rtcd)" || {
        echo "❌ Test VMs not found. Run: $0 create"
        exit 1
    }
    echo "✓ VMs are running"
}

case "${1:-}" in
    create)
        create_vms
        setup_inventory
        echo ""
        echo "Next steps:"
        echo "  1. Verify VMs: make test-integration-check-vms"
        echo "  2. Run tests: make test-integration"
        ;;
    delete)
        delete_vms
        ;;
    setup-inventory)
        setup_inventory
        ;;
    verify)
        verify_vms
        ;;
    *)
        echo "Usage: $0 {create|delete|setup-inventory|verify}"
        echo ""
        echo "Commands:"
        echo "  create           Create test VMs and generate test.ini"
        echo "  delete           Delete test VMs"
        echo "  setup-inventory  Generate test.ini (VMs must exist)"
        echo "  verify           Check if test VMs are running"
        exit 1
        ;;
esac
