{
 "title": "Mattermost Mobile Performance Metrics",
 "description": "A dashboard to review Mattermost mobile performance metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "rate", "query": "${VAR_RATE}" },
   { "name": "percentile", "query": "0.99, 0.95, 0.90, 0.75" }
  ]
 },
 "panels": [
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "Load times between the moment the app is initialized and the moment the target screen (Home, Channel or Thread) is shown in the screen.\n\nEach point in the graph shows the percentile of the  events during the last hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_load_bucket{}[$rate])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_load_bucket{platform=\"android\"}[$rate])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_load_bucket{platform=\"ios\"}[$rate])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load lifetime percentiles",
   "type": "stat",
   "description": "Load times between the moment the app is initialized and the moment the target screen (Home, Channel or Thread) is shown in the screen.\n\nThese values represent the percentile of all events since the last metrics restart.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_load_bucket{}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_load_bucket{platform=\"android\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_load_bucket{platform=\"ios\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Events load",
   "type": "timeseries",
   "description": "Load times between the moment the app is initialized and the moment the target screen (Home, Channel or Thread) is shown in the screen.\n\nThis graph represents all events generated since the last metrics restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(mattermost_mobileapp_mobile_load_count{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_load_count{platform=\"android\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_load_count{platform=\"ios\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Events Load",
   "type": "stat",
   "description": "Load times between the moment the app is initialized and the moment the target screen (Home, Channel or Thread) is shown in the screen.\n\nThese numbers represent the number of events since the last metrics restart.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mattermost_mobileapp_mobile_load_count{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_load_count{platform=\"android\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_load_count{platform=\"ios\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Channel Switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Channel Switch",
   "type": "timeseries",
   "description": "Channel switch represents the time between the user clicks on a channel name, and the app shows the latest post in that channel.\n\nEach point in the graph shows the percentile of the  events during the last hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_channel_switch_bucket{}[$rate])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_channel_switch_bucket{platform=\"android\"}[$rate])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_channel_switch_bucket{platform=\"ios\"}[$rate])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel switch lifetime percentiles",
   "type": "stat",
   "description": "Channel switch represents the time between the user clicks on a channel name, and the app shows the latest post in that channel.\n\nThese values represent the percentile of all events since the last metrics restart.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_channel_switch_bucket{}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_channel_switch_bucket{platform=\"android\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_channel_switch_bucket{platform=\"ios\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Events Channel Switch",
   "type": "timeseries",
   "description": "Channel switch represents the time between the user clicks on a channel name, and the app shows the latest post in that channel.\n\nThis graph represents all events generated since the last metrics restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(mattermost_mobileapp_mobile_channel_switch_count{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_channel_switch_count{platform=\"android\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_channel_switch_count{platform=\"ios\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Events Channel Switch",
   "type": "stat",
   "description": "Channel switch represents the time between the user clicks on a channel name, and the app shows the latest post in that channel.\n\nThese numbers represent the number of events since the last metrics restart.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mattermost_mobileapp_mobile_channel_switch_count{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_channel_switch_count{platform=\"android\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_channel_switch_count{platform=\"ios\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Team switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Mobile Team switch",
   "type": "timeseries",
   "description": "Team switch represents the time between the user taps on a team, and the full category screen changes to the one of the new team.\n\nEach point in the graph shows the percentile of the  events during the last hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_team_switch_bucket{}[$rate])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_team_switch_bucket{platform=\"android\"}[$rate])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (rate(mattermost_mobileapp_mobile_team_switch_bucket{platform=\"ios\"}[$rate])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Team Switch lifetime percentiles",
   "type": "stat",
   "description": "Team switch represents the time between the user taps on a team, and the full category screen changes to the one of the new team.\n\nThese values represent the percentile of all events since the last metrics restart.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_team_switch_bucket{}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_team_switch_bucket{platform=\"android\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le) (mattermost_mobileapp_mobile_team_switch_bucket{platform=\"ios\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Events Team Switch",
   "type": "timeseries",
   "description": "Team switch represents the time between the user taps on a team, and the full category screen changes to the one of the new team.\n\nThis graph represents all events generated since the last metrics restart.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(mattermost_mobileapp_mobile_team_switch_count{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_team_switch_count{platform=\"android\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_team_switch_count{platform=\"ios\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Events Team Switch",
   "type": "stat",
   "description": "Team switch represents the time between the user taps on a team, and the full category screen changes to the one of the new team.\n\nThese numbers represent the number of events since the last metrics restart.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mattermost_mobileapp_mobile_team_switch_count{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_team_switch_count{platform=\"android\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mattermost_mobileapp_mobile_team_switch_count{platform=\"ios\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}