{
 "title": "Mattermost Notification Health",
 "description": "This dashboard can be used to track the different types of notifications sent from Mattermost.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Websocket Notification Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$Acked/$Sent", "type": "math" }
   ]
  },
  {
   "title": "Push Notification Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$Acked/$Sent", "type": "math" }
   ]
  },
  {
   "title": "Websocket Notification Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(mattermost_notifications_total{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Notifiable Events Sent"
    },
    {
     "expr": "sum(mattermost_notifications_total_ack{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Notifiable Events Acknowledged"
    },
    { "expression": "$Sent-$Acked", "type": "math" }
   ]
  },
  {
   "title": "Websocket Sent vs. Not Sent",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(mattermost_notifications_unsupported{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Total Notifications Unknown"
    },
    {
     "expr": "sum(mattermost_notifications_not_sent{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Total Notifications Not Sent"
    },
    {
     "expr": "sum(mattermost_notifications_success{type=\"websocket\"}) OR vector(0)",
     "legendFormat": "Total Notifications Sent"
    }
   ]
  },
  {
   "title": "Push Notification Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(mattermost_notifications_total{type=\"push\"}) OR vector(0)",
     "legendFormat": "Push Notifications Sent"
    },
    {
     "expr": "sum(mattermost_notifications_total_ack{type=\"push\"}) OR vector(0)",
     "legendFormat": "Push Notifications Acknowledged"
    },
    { "expression": "$Sent-$Acked", "type": "math" }
   ]
  },
  {
   "title": "Websocket Notification Errors by Reason",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_error{type=\"websocket\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Websocket Notifications Not Sent Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_not_sent{type=\"websocket\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Push Notification Errors by Reason",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_error{type=\"push\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Push Notifications Not Sent Distribution",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (mattermost_notifications_not_sent{type=\"push\"})",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Email Notifications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (max_over_time(mattermost_notifications_not_sent{type=\"email\"}[$__range]) or vector(0) - max_over_time(mattermost_notifications_not_sent{type=\"email\"}[$__range] offset $__range))",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum by(reason) (max_over_time(mattermost_notifications_error{type=\"email\"}[$__range]) or vector(0) - max_over_time(mattermost_notifications_error{type=\"email\"}[$__range] offset $__range))",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}