---
- name: Prepare
  hosts: app
  become: true
  gather_facts: false
  tasks:
    - name: Install firewalld and python-firewall for testing
      ansible.builtin.package:
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: Start firewalld service
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
