---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    # Install nginx as certbot depends on it
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started

  roles:
    - certbot
