---
# calls-offloader role handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart calls-offloader
  ansible.builtin.systemd:
    name: calls-offloader
    state: restarted
