---
galaxy_info:
  author: Mattermost
  description: coturn TURN/STUN server for Mattermost Calls
  license: ""
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - mattermost
    - coturn
    - turn
    - stun
    - webrtc

dependencies: []
