---
galaxy_info:
  author: Mattermost
  description: Docker Engine installation for calls-offloader
  license: ""
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - mattermost
    - docker
    - containers

dependencies: []
